version: '3.8'

services:
  backend:
    # Nombre del contenedor
    container_name: nodevet_backend_app
    
    # Le decimos que construya la imagen usando el Dockerfile de esta misma carpeta
    build:
      context: .
      dockerfile: Dockerfile
      
    # Conectamos el puerto de tu compu con el del contenedor
    ports:
      - "8080:8080"
      
    # Le pasamos el archivo con las credenciales de AWS
    env_file:
      - .env
    
    environment:
      - FLOW_CONFIRM_URL=http://23.20.131.31:8080/api/v1/pagos/webhook
      
    # Si el contenedor se cae por algún error, Docker lo reiniciará automáticamente
    restart: unless-stopped